spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/crm}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: crm-group

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 87666842618-3uahf7e2oqom1fqbsj2ld3b9jlppjhia.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo

server:
  port: 8080

logging:
  level:
    root: INFO
